name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-messages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kaste/upgrade-messages-test-action@v1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: TrueBrain/actions-flake8@v2
